stages:
- name: Publish image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: php-example:${CICD_EXECUTION_SEQUENCE}
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deploy/deployment.yaml
notification:
  recipients:
  - recipient: rancher-notifications
    notifier: c-b44lv:n-pd8jp
  condition:
  - Success
  - Changed
  - Failed
